#!/bin/bash
# to run the flask website

if [ "$1" == "-h" ]
then
  echo "$0 [--local]"
  echo "  --local  run local only for debugging"
  exit 0
fi
if [ "$1" == "--local" ]
then
    #if [ "$(uname -a)" == "Darwin" ]
    #then
    #  python3 -m http.server -d / 80 &
    #  pid=$!
    #fi
    # for local only connections
    cd ../
    flask --app flaskr --debug run

    #kill $pid
else
    # for external connections
    cd ../
    #screen -S urban -dm flask --app flaskr --debug run --host=0.0.0.0
    flask --app flaskr --debug run --host=0.0.0.0 > $HOME/.local/share/urban.log 2>&1

fi
